### ISSUE TITLE
Core dump depending on simulation/lattice variable scope

### ISSUE THREAD

**Issue by e-carlin** [fnalacceleratormodeling/synergia2#106]
Hi - I'm running into a core dump issue using synergia. It seems to depend on the scope of the simulation and/or lattice variables.

Steps to reproduce:
- compile from [synergia3-2022.11](https://github.com/fnalacceleratormodeling/synergia2/releases/tag/synergia3-2022.11) 
- apply the below patch to the [wiki example](https://github.com/fnalacceleratormodeling/synergia2/wiki/FODO-example-in-Python). This patch is a simple contrived example to show the bug. In reality I have code generating a simulation and it generates a script with all code at the outer most scope of the script (no functions). 
```
~$ patch synergia-example-from-web.py <<'EOF'
> @@ -98,14 +98,15 @@

     # save
     synergia.simulation.checkpoint_save(propagator, sim)
+    return sim


 def main():

     try:
-        run()
+        return run()
     except:
         raise RuntimeError("Failure to launch fodo.run")


-main()
+sim = main()
> EOF
```
- See error:
```
~$ python synergia-example-from-web.py
Propagator: starting turn 1, final turn 10
<SNIP>
Propagator: maximum number of turns reached
Propagator: total time = 5.293s
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos allocation "corr" is being deallocated after Kokkos::finalize was called
```

Turning on DEBUG level logging in the simlog object doesn't yield any additional information about the possible cause.

Do you have any idea what might be causing this? Is there a way to resolve it?

Let me know if I can provide more info. Thanks for your help.

**Comment by egstern** [comment]
I think what you are seeing is that all classes and objects that hold Kokkos objects have to be destroyed either by going out-of-scope or explicit del in Python before the program terminates. It looks like you are trying to sneak sim object out of the run() into the top level.

**Comment by e-carlin** [comment]
Aha, thanks @egstern. So it is about the scoping. I guess I'll modify the generation code to cope the variables or do a del. I appreciate the speedy reply.
